### ISSUE TITLE
Error message: Inconsistent number of files

### ISSUE THREAD

**Issue by chenyugoal** [iTCf/anonymi#1]
I have 200 T1-weighted MR images to anonymize. They are all in nifti format (*.nii.gz). I put them in one folder. Then I prepared the files following the instructions in the README file. After the data preparation, I have 200 (the original MRI) + 800 (*.txt, *tfm, *vtk) files in the folder. I selected the *_outer_skin_surface.vtk in the "Automatic Processing" section and clicked on the "Run" button. It throwed me the following error message:

^^^
---> Running Batch
- (1/1)Input file: KKI2009-05-MPRAGE_reoriented_outer_skin_surface.vtk
{'skin': '/home/cgao/projects/Defacing/AnonyMI/Data_prepare/KKI2009-05-MPRAGE_reoriented_outer_skin_surface.vtk', 'skull': '/home/cgao/projects/Defacing/AnonyMI/Data_prepare/KKI2009-05-MPRAGE_reoriented_outer_skull_surface.vtk', 'trans': '/home/cgao/projects/Defacing/AnonyMI/Data_prepare/KKI2009-05-MPRAGE_reoriented_surf2mri.tfm', 'mri': '/home/cgao/projects/Defacing/AnonyMI/Data_prepare/KKI2009-05-MPRAGE_reoriented.nii.gz'}

-->Inconsistent number of files

skin: 1
skull: 1
trans: 1
mri: 1

Please check if you have more than one file type with the same name
^^^

But after checking the folder, I didn't find such kind of problems.

**Comment by chenyugoal** [comment]
I looked into Anonymi.py and found that the `if` statement in line 332 will always be true because len() will return the length of the string (a path).

**Comment by ezemikulan** [comment]
Hi, thanks for reporting the issue. I'm looking into it, I'll be back soon with an answer

**Comment by ezemikulan** [comment]
It should be fixed now. Please update the script. Let me know if you need anything else or if you find other issues.

Thanks! 

PS: If you are using Slicer version 5 there might be some temporary folders that are created while saving that are not automatically deleted due to an upstream bug. You can safely delete them. I'll keep a eye on this an push an update if needed.

**Comment by chenyugoal** [comment]
Thank you! @ezemikulan 
Just want to make sure that the updated script has no influence on the data preparation step, right? So that I don't need to re-run the preparation.

**Comment by ezemikulan** [comment]
Yes, that's correct, you can use the already prepared files

**Comment by chenyugoal** [comment]
It's running without throwing error messages now. Thank you!

**Comment by ezemikulan** [comment]
Great, thanks!

PS: If you have suggestions to improve the the user experience please let us know
