### ISSUE TITLE
Slicer Not Responding

### ISSUE THREAD

**Issue by birnybaum** [iTCf/anonymi#2]
I followed all of the steps to install anonymi and slicer. I added the extensions and modules needed. I also got the FreeSurfer license. I was getting errors on Linux and used "chmod 755 *"  to solve the issues.  Now every time I try running the preprocessing step, slicer stops responding and has to be shut down. I tried uninstalling and reinstalling, I even used different versions of slicer. 

I am using a virtual machine with Ubuntu 22.04.3.

**Comment by birnybaum** [comment]
It was a problem with the virtual machine. The allocated resources were being used up causing slicer to shut down.

**Comment by ezemikulan** [comment]
Hi, sorry about the delay, I never got notified, good to know that you could solve the issue, if you need anything else let us know.
